### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ashes999** [MuslimGamer/house-of-jinns#1]
**Vision:** Procedually generated mansion. The player wakes in a bedroom with no idea of how he got there. The house is dark and seemingly abandoned. A Jinn roams the house searching for the player, who must move around the house avoiding it and hiding while searching for keys/tools to help him escape.

**TODO:** create a weekly sub-issue for @AbrarSyed to work on

# Prototype
- [x] Basic repository with prototyping library
- [x] Player moves around with keys
- [x] Player moves with gamepad
- [x] Game is full screen!
- [ ] Procedurally generated building
  - [x] Player can move from room to room
  - [x] Doors can be locked
  - [x] Keys exist for doors (any key works for any door)
  - [x] Rooms are dark until entered. Only the current room is lit.
  - [x] Big Boo style jinn that wanders randomly. He can go through walls.
  - [ ] Journal pages (placeholder) -- collect all three to win? (Put "3" in `external.json`)
  - [ ] Random objects in rooms. Beds, desks, etc.
  - [ ] Left-click to examine objects
  - [ ] Right-click: can hide under bed
  - [ ] Right-click: Can open locked door with key
  - [ ] Right-click: hide in cupboard
- [ ] Collectables: walk into them to collect
- [ ] Catch up gamepad support for left/right click
- [ ] Design
  - [ ] Story
  - [ ] Gameplay objectives

# MVP

TBD

**Comment by ashes999** [comment]
Moved to Trello
